### ISSUE TITLE
API on DigitalOcean

### ISSUE THREAD

**Issue by nikdo** [nikdo/wfx-api#35]
API is running on DigitalOcean droplet so that the database is not open to the whole universe.

## Reasoning

Currently, MongoDB port at DigitalOcean VPS is opened to the whole world because [Heroku does not provide static IP address in a basic plan](https://help.heroku.com/JS13Y78I/i-need-to-whitelist-heroku-dynos-what-are-ip-address-ranges-in-use-at-heroku) to limit requests. Also, DigitalOcean reported that opening a database port without restrictions is a security issue.

### Identified options

1. Purchase static IP on Heroku. *No: Expensive.*
2. Migrate DB from DigitalOcean to Heroku MongoDB plugin. *No: Still expensive. Plus I'll need access to DB for periodical forecast notifications on DigitalOcean in the future.*
3. Migrate the whole app from Heroku to DigitalOcean. *No: A lot of infrastructure to set up.*
4. Migrate API from Heroku to DigitalOcean. *Yes.*

**Comment by nikdo** [comment]
# Tasks

## Spike app

- [ ] install Node.js on DigitalOcean
- [ ] write spike app that operates on certain port

## Separate repo

- [ ] create a separate repo for API
- [ ] copy API code to a separate repo
- [ ] update API repo README

## Deploy API

- [ ] find out how to set env variables on DigitalOcean
- [ ] set Dark Sky key to env variable on DigitalOcean
- [ ] investigate DigitalOcean deployment options
- [ ] set up the simplest deployment process
- [ ] update README to include deployment process
- [ ] deploy API
- [ ] test localhost client with API
- [ ] test Heroku client with API

## Remove API from client

- [ ] remove API from client repo
	- [ ] add variable with API URL
	- [ ] restructure project
	- [ ] remove serving client from the 
	- [ ] change Heroku build hooks
	- [ ] remove Heroku env variables
- [ ] update client repo README
